#!/usr/bin/env bash
# aos_gov_stamp.sh — write _aos/AOS_GOVERNANCE_VERSION.yaml (Model B / ADR054).
#
# The version stamp is the ONLY governance artifact that remains TRACKED in a
# domain's git history under Model B. It answers "which governance version does
# this domain hold?" at any past commit. Generated, never hand-edited (CS-6).
#
# Prereqs: git, find, date. Env: ACTOR (optional, recorded as synced_by),
#   AOS_HUB_SHA / AOS_HUB_REF (optional fallback when hub_root is a remote URL).
# Ports: none.
#
# Usage: write_gov_stamp <target_repo> <hub_root|hub_url> [synced_by]

write_gov_stamp() {
  local target_repo="$1"
  local hub_root="$2"
  local synced_by="${3:-${ACTOR:-unknown}}"
  [ -d "$target_repo/_aos" ] || return 0

  local hub_sha hub_short hub_ref ts count d tmp
  if git -C "$hub_root" rev-parse HEAD >/dev/null 2>&1; then
    hub_sha="$(git -C "$hub_root" rev-parse HEAD)"
    hub_short="$(git -C "$hub_root" rev-parse --short=12 HEAD)"
    hub_ref="$(git -C "$hub_root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
  else
    # hub_root is a remote URL (CI git-archive path) — use env fallbacks.
    hub_sha="${AOS_HUB_SHA:-unknown}"
    hub_short="${hub_sha:0:12}"
    hub_ref="${AOS_HUB_REF:-main}"
  fi
  ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  count=0
  for d in governance methodology lean-kit; do
    if [ -d "$target_repo/_aos/$d" ]; then
      count=$(( count + $(find "$target_repo/_aos/$d" -type f 2>/dev/null | wc -l | tr -d ' ') ))
    fi
  done

  tmp="$target_repo/_aos/.AOS_GOVERNANCE_VERSION.yaml.tmp"
  cat > "$tmp" <<EOF
# _aos/AOS_GOVERNANCE_VERSION.yaml — TRACKED governance audit anchor (Model B / ADR054).
# Generated by aos_sync_all.sh / aos_governance_bootstrap.sh. Do NOT hand-edit.
schema: aos.governance.version/v1
hub_repo: WaldNimrod/agents-os
hub_sha: ${hub_sha}
hub_sha_short: ${hub_short}
hub_ref: ${hub_ref}
synced_at: ${ts}
synced_by: ${synced_by}
cache_paths: [_aos/governance/, _aos/methodology/, _aos/lean-kit/]
cache_file_count: ${count}
EOF
  mv -f "$tmp" "$target_repo/_aos/AOS_GOVERNANCE_VERSION.yaml"
}
